// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/AboutUs.tsx";
import * as $$$$$$1 from "./sections/ContactUs.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/HeroBText.tsx";
import * as $$$$$$4 from "./sections/HeroColors.tsx";
import * as $$$$$$5 from "./sections/HeroGrid.tsx";
import * as $$$$$$6 from "./sections/HeroImage.tsx";
import * as $$$$$$7 from "./sections/HeroManyBanners.tsx";
import * as $$$$$$8 from "./sections/HeroMidBanner.tsx";
import * as $$$$$$9 from "./sections/Instagram.tsx";
import * as $$$$$$10 from "./sections/ItWorks.tsx";
import * as $$$$$$11 from "./sections/Maps.tsx";
import * as $$$$$$12 from "./sections/SimpleBannerText.tsx";
import * as $$$$$$13 from "./sections/SliderImages.tsx";
import * as $$$$$$14 from "./sections/Theme/Header.tsx";
import * as $$$$$$15 from "./sections/Theme/Theme.tsx";
import * as $$$$$$16 from "./sections/WhatsApp.tsx";

const manifest = {
  "sections": {
    "site/sections/AboutUs.tsx": $$$$$$0,
    "site/sections/ContactUs.tsx": $$$$$$1,
    "site/sections/Footer.tsx": $$$$$$2,
    "site/sections/HeroBText.tsx": $$$$$$3,
    "site/sections/HeroColors.tsx": $$$$$$4,
    "site/sections/HeroGrid.tsx": $$$$$$5,
    "site/sections/HeroImage.tsx": $$$$$$6,
    "site/sections/HeroManyBanners.tsx": $$$$$$7,
    "site/sections/HeroMidBanner.tsx": $$$$$$8,
    "site/sections/Instagram.tsx": $$$$$$9,
    "site/sections/ItWorks.tsx": $$$$$$10,
    "site/sections/Maps.tsx": $$$$$$11,
    "site/sections/SimpleBannerText.tsx": $$$$$$12,
    "site/sections/SliderImages.tsx": $$$$$$13,
    "site/sections/Theme/Header.tsx": $$$$$$14,
    "site/sections/Theme/Theme.tsx": $$$$$$15,
    "site/sections/WhatsApp.tsx": $$$$$$16,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
